#!/bin/bash
FLAG=$1
OPTARG=$2
NAME=$3
IPADDR=$4
ZONE=$5
while getopts 't:' OPTION; do
  case "$OPTION" in
    t)
	if [ $OPTARG == A ]
		then
			echo "WRITE A RECORD"
			echo ";Name Server Records" 			>>/etc/bind/zones/db.$ZONE
			echo "${NAME}	IN	A	${IPADDR}" 	>>/etc/bind/zones/db.$ZONE	
      			echo "WOOP it works $OPTARG $NAME $ZONE"
	elif [ $OPTARG == MX ]
		then	
			#CREATE A RECORD
			echo "WRITE A RECORD"
                        echo ";Name Server Records"                     >>/etc/bind/zones/db.$ZONE
                        echo "${NAME}   IN      A       ${IPADDR}"      >>/etc/bind/zones/db.$ZONE
                        echo "WOOP it works $OPTARG $NAME $ZONE"

			echo "WRITE MX RECORD"
                        echo ";Name Server MX"				>>/etc/bind/zones/db.$ZONE
			echo "@	IN	MX	${NAME}.${ZONE}"	>>/etc/bind/zones/db.$ZONE
	elif [ $OPTARG == CNAME ]
                then
			echo "WRITE CNAME RECORD"
			echo ";Name Server CNAME"			>>/etc/bind/zones/db.$ZONE
                        echo "${NAME}	IN	CNAME	${IPADDR}."	>>/etc/bind/zones/emile-hermans.sb.uclllabs.be
			echo "WOOP it works $OPTARG $NAME $IPADDR $ZONE"
	else
			echo "Provided $OPTARG"
		fi

  esac
done
shift "$(($OPTIND -1))"

FSERIAL=($(sed -n '6p' < /etc/bind/zones/db.$ZONE))
LSERIAL=$(($FSERIAL + 1))
sed -i '6s/'"${FSERIAL}"'/'"${LSERIAL}"'/' /etc/bind/zones/db.$ZONE

rndc reload
systemctl restart bind9
