#!/bin/bash

SUBDOMAIN=$1

DOMAIN="${SUBDOMAIN}.conf"

NAME=`echo $SUBDOMAIN | grep -Po '.*(?=.emile-hermans.sb.uclllabs.be)'`
#create A record in dns server

echo "Add A record to dns with name: ${NAME}"
dns_add_record -t B $NAME 193.191.177.152 

echo "Making dir with path /var/www/${NAME}"
mkdir /var/www/$NAME


#Make HTML FILE
echo "Creating html file with ${NAME}"
echo "<!DOCTYPE html>"						>>/var/www/$NAME/index.html
echo "<html>"							>>/var/www/$NAME/index.html
echo "welcome vhost_name"					>>/var/www/$NAME/index.html
echo "welcome ${SUBDOMAIN}"					>>/var/www/$NAME/index.html
echo "</html>"							>>/var/www/$NAME/index.html
echo "HTML file created"


#Create virtual host
echo "Creating vhost with name ${NAME}"
echo "<virtualHost *:80>"					>>/etc/apache2/sites-available/$NAME.conf
echo "ServerName ${SUBDOMAIN}"					>>/etc/apache2/sites-available/$NAME.conf
echo "ServerAlias ${SUBDOMAIN}"					>>/etc/apache2/sites-available/$NAME.conf
echo "DocumentRoot /var/www/${NAME}/"				>>/etc/apache2/sites-available/$NAME.conf

echo "ErrorLog ${APACHE_LOG_DIR}/error.log"			>>/etc/apache2/sites-available/$NAME.conf
echo "CustomLog ${APACHE_LOG_DIR}/access.log combined"		>>/etc/apache2/sites-available/$NAME.conf
echo "</virtualhost>"						>>/etc/apache2/sites-available/$NAME.conf

echo "vhost created"
#Enable new vhost
a2ensite $NAME.conf
echo "vhost enabled"

apache2ctl configtest
systemctl restart apache2
systemctl status apache2
echo "All done"
