#!/bin/bash

#start
  start_firewall() {
    ip6tables-restore < /etc/iptables/rules.v6
    iptables-restore < /etc/iptables/rules.v4

    echo 0 > /proc/sys/net/ipv4/ip_forward
    echo 1 > /proc/sys/net/ipv4/tcp_syncookies
  }

#stop
  stop_firewall() {
    ip6tables -F
    iptables -F
    echo 1 > /proc/sys/net/ipv4/ip_forward
    echo 0 > /proc/sys/net/ipv4/tcp_syncookies
  }
# Handle command line arguments
case "$1" in
  start)
    start_firewall
    ;;
  stop)
    stop_firewall
    ;;

  restart)
   stop_firewall
   start_firewall
    ;;
  *)
    echo "Usage: firewall {start|stop|restart}"
    exit 1
    ;;
esac
