#!/bin/bash

# Start the firewall
start_firewall() {
  # Allow incoming traffic on TCP port 25
    iptables -A INPUT -p tcp --dport 25 -j ACCEPT
    iptables -A INPUT -p tcp --dport 80 -j ACCEPT
    iptables -A INPUT -p tcp --dport 443 -j ACCEPT
    iptables -A INPUT -p tcp --dport 587 -j ACCEPT
    iptables -A INPUT -p tcp --dport 993 -j ACCEPT
    iptables -A INPUT -p tcp --dport 22345 -j ACCEPT

    iptables -A INPUT -p tcp --dport 53 -j ACCEPT
    iptables -A INPUT -p udp --dport 53 -j ACCEPT

  # Permit by ip 
    iptables -A INPUT -s 10.0.0.0/8 -j ACCEPT
    iptables -A INPUT -s 192.168.255.0/24 -j ACCEPT
    iptables -A INPUT -s 172.16.0.0/16 -j ACCEPT

  # Allow mrt and leia
    iptables -A INPUT -s mrt.uclllabs.be -j ACCEPT
    iptables -A INPUT -s leia.uclllabs.be -j ACCEPT
  # Allow icmp ping resuest	
    iptables -A INPUT -p icmp -j ACCEPT

  # Drop all other traffic
    iptables -A INPUT -j DROP

  # Disable ip routing
    iptables -I FORWARD -j DROP
}

# Stop the firewall
stop_firewall() {
  # Flush/clear all rules
    iptables -F
}

# Restart firewall
restart_firewall() {
  # Stop firewall
    stop_firewall()
  # Start firewall
    start_firewall()
}

# Handle command line arguments
case "$1" in
  start)
    start_firewall
    ;;
  stop)
    stop_firewall
    ;;
  restart)
    restart_firewall
    ;;
  *)
    echo "Usage: firewall {start|stop|restart}"
    exit 1
    ;;
esac
