#!/bin/bash

# Start the firewall
start_firewall() {
    iptables -A INPUT -p tcp --dport 25 -j ACCEPT 
    iptables -A INPUT -p tcp --dport 80 -j ACCEPT
    iptables -A INPUT -p tcp --dport 443 -j ACCEPT
    iptables -A INPUT -p tcp --dport 587 -j ACCEPT
    iptables -A INPUT -p tcp --dport 993 -j ACCEPT 
    iptables -A INPUT -p tcp --dport 22345 -j ACCEPT

    iptables -A INPUT -p tcp --dport 53 -j ACCEPT
    iptables -A INPUT -p udp --dport 53 -j ACCEPT
    

  # ipv6
    ip6tables -A INPUT -p tcp --dport 25 -j ACCEPT
    ip6tables -A INPUT -p tcp --dport 80 -j ACCEPT
    ip6tables -A INPUT -p tcp --dport 443 -j ACCEPT
    ip6tables -A INPUT -p tcp --dport 587 -j ACCEPT
    ip6tables -A INPUT -p tcp --dport 993 -j ACCEPT
    ip6tables -A INPUT -p tcp --dport 22345 -j ACCEPT

    ip6tables -A INPUT -p tcp --dport 53 -j ACCEPT 
    ip6tables -A INPUT -p udp --dport 53 -j ACCEPT 

  # Permit by ip 
    iptables -A INPUT -s 10.0.0.0/8 -j ACCEPT
    iptables -A INPUT -s 192.168.255.0/24 -j ACCEPT
    iptables -A INPUT -s 172.16.0.0/16 -j ACCEPT

  # Allow mrt and leia
    iptables -A INPUT -s  193.191.177.6 -j ACCEPT
    iptables -A INPUT -s  193.191.177.1 -j ACCEPT

    ip6tables -A INPUT -s 2001:6a8:2880:a021::6/128 -j ACCEPT 
    ip6tables -A INPUT -s 2001:6a8:2880:a021::1/128 -j ACCEPT
    -A INPUT -m state --state ESTABLISHED -j ACCEPT 
  # Allow icmp ping resuest	
    iptables -A INPUT -p icmp -j ACCEPT
    ip6tables -A INPUT -p ipv6-icmp -j ACCEPT

  # Drop all other traffic
    iptables -A INPUT -j DROP
    ip6tables -A INPUT -j DROP

  # Disable ip routing
    iptables -I FORWARD -j DROP

  # Enable tcp syn cookies
    sed -i 's/net.ipv4.tcp_syncookies=0/net.ipv4.tcp_syncookies=1/g' /etc/sysctl.conf
  #Save
  /sbin/iptables-save > /etc/iptables/rules.v4
  /sbin/ip6tables-save > /etc/iptables/rules.v6
}

# Stop the firewall
stop_firewall() {
  # Flush/clear all rules
    iptables -F
    ip6tables -F

  #Save
  /sbin/iptables-save

  /sbin/iptables-restore > /etc/iptables/rules.v4
  /sbin/ip6tables-restore >  /etc/iptables/rules.v6  
}

# Restart firewall
restart_firewall() {
  # Stop firewall
    stop_firewall
  # Start firewall
    start_firewall
}

# Handle command line arguments
/sbin/iptables-restore < /etc/iptables/rules.v4
/sbin/ip6tables-restore <  /etc/iptables/rules.v6

echo 0 > /proc/sys/net/ipv4/ip_forward
echo 1 > /proc/sys/net/ipv4/tcp_syncookies
case "$1" in
  start)
    start_firewall
    ;;
  stop)
    stop_firewall
    ;;
  restart)
   restart_firewall
    ;;
  *)
    echo "Usage: firewall {start|stop|restart}"
    exit 1
    ;;
esac
